### ISSUE TITLE
PropTypes.shape support is missing.

### ISSUE THREAD

**Issue by 40818419** [blueberryapps/react-bluekit#96]
```
PropsTable.react.js:127
Uncaught TypeError: data.getIn is not a function
    at RadiumEnhancer.renderPropTableRow (http://localhost:8080/dist/example.js:64575:24)
    at http://localhost:8080/dist/example.js:43414:47
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate (http://localhost:8080/dist/example.js:42135:25)
    at Map.__iterate (http://localhost:8080/dist/example.js:41773:33)
    at http://localhost:8080/dist/example.js:41620:17
    at Map.withMutations (http://localhost:8080/dist/example.js:41751:8)
    at Array.map (native)
    at RadiumEnhancer.render (http://localhost:8080/dist/example.js:64549:26)
    at RadiumEnhancer.render (http://localhost:8080/dist/example.js:45627:66)
    at measureLifeCyclePerf (http://localhost:8080/dist/example.js:23563:13)
```

**Comment by ondrejbartas** [comment]
Hi, this is strange. PropType.shape should be working. We have some examples whit it.

https://github.com/blueberryapps/react-bluekit/blob/master/example_components/MultiField.react.js#L13-L17

can you send your propTypes pls?

**Comment by 40818419** [comment]
Ah... i have it like this:

https://github.com/40818419/react-code-input/blob/master/src/index.js#L153-L165

**Comment by ondrejbartas** [comment]
It should be working.

**Comment by apfelfabrik** [comment]
Found this issue when running in a very similar problem: `Uncaught TypeError: data.getIn is not a function` related to a component using `PropTypes.shape`.

**Comment by apfelfabrik** [comment]
@ondrejbartas The example you posted above works because `arrayOf` renders a JSON editor without respecting the contained `propType`. Using `PropTypes.shape` as a first level prop consistently fails with the error @40818419 reported and I'm experiencing.

**Comment by apfelfabrik** [comment]
PR might illustrate the problem, not sure this restores the intended behaviour though.

**Comment by imtoo** [comment]
It seems it solved the problem. Thanks guys!
